server {
    listen 8080;
    server_name _;
    client_max_body_size 50m;

    # admin-web 前端 SPA
    location / {
        root /usr/share/nginx/html/admin-web;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # admin API（前端 prod build 走 /prod-api 前缀）
    location /prod-api/ {
        rewrite ^/prod-api/(.*) /admin/$1 break;
        proxy_pass http://localhost:9010;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
